DROP TABLE IF EXISTS route_plane;
DROP TABLE IF EXISTS routes;
DROP TABLE IF EXISTS airlines;
DROP TABLE IF EXISTS airports;
DROP TABLE IF EXISTS cities;
DROP TABLE IF EXISTS planes;
DROP TABLE IF EXISTS countries;

-- DROP DATABASE IF EXISTS openflights;